# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "raring_ringtail_64"
  config.vm.provision "shell", path: "../debian/install.sh"
  config.vm.box_url = "http://goo.gl/ceHWg"

end
