# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "squeeze"
  config.vm.box_url = "http://vagrantboxes.footballradar.com/wheezy64.box"
  config.vm.network :forwarded_port, :guest => 80, :host => 2345
  config.vm.provision :shell do |shell|
    shell.inline = "curl -L https://www.opscode.com/chef/install.sh | bash; apt-get update"
  end
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "graphite"
  end
end
